openapi: 3.0.3
info:
  title: Welbex-blog-app
  version: 0.0.1
servers:
  - url: https://welbex-task-blog.vercel.app/api
    description: Dev server
paths:
  /user/register:
    post:
      tags:
        - user
      description: Create new user
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          headers:
            authorization:
              schema:
                type: string
              description: "Bearer accesstoken"
  /user/login:
    post:
      tags:
        - user
      description: User login returns authorization header with Bearer token
      parameters:
        - name: email
          in: query
          description: The user email for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers:
            authorization:
              schema:
                type: string
              description: "Bearer accesstoken"
        '401':
          description: Invalid username/password supplied
  /post:
    get:
      tags:
      - post
      description: Returns array 20 posts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                       $ref: '#/components/schemas/Post'
                  count:
                    type: number
  /post/create:
    get:
      tags:
        - post
      description: Create new post
      parameters:
        - name: authorization
          in: header
          type: string
          description: "Bearer accesstoken"
          required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /post/edit:
    post:
      tags:
        - post
      description: Edit post
      parameters:
        - name: authorization
          in: header
          type: string
          description: "Bearer accesstoken"
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /post/delete/{postId}:
    delete:
      tags:
        - post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      parameters:
        - name: authorization
          in: header
          type: string
          description: "Bearer accesstoken"
          required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: int64
          example: '394lfhbohf3398y3'
        name:
          type: string
          example: theUser
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
      xml:
        name: user
    Post:
      type: object
      properties:
        id:
          type: string
          format: int64
          example: '394lfhbohf3398y3'
        title:
          type: string
          format: int64
          example: '394lfhbohf3398y3'
        content:
          type: string
          format: int64
          example: 'lorem ipsum...'
          required: false
        imagePath:
          type: string
        xml:
          name: post